name: Validate with hassfest and HACS

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
        - uses: "actions/checkout@v4"
        - name: HACS validation
          uses: "hacs/action@main"
          with:
            category: "integration"
        - name: HA validation
          uses: "home-assistant/actions/hassfest@master"
